export const descriptions = [
  'ChatGPT, plase introduce me.',
  'Computing for fun.',
  'I am a software developer.',
  'Certified Software Developer, certified Mexican.',
  'Just a guy who likes to code.',
  'How much wood would a woodchuck chuck if a woodchuck could chuck wood?',
  'Is this the real life? Is this just fantasy?',
  'Running out of ideas for descriptions.',
  'Desarrollador de software.',
  'パワーレンジャーが好きな人.',
  'Developing since 2019 and still going strong.',
  'Alexa, play Despacito.',
  'Alexa, reproduce el triste de Jose Jose.',
  'I am a mobile and web developer with solid knowledge in JavaScript using React.js and React-Native.',
  'Messing around with code.',
  'Alexa, play 911 by Lady Gaga.',
  'Alexa, play brat by Charli XCX.',
  'Alexa, play 100 gecs.',
  'LinkedIn is the new Facebook.',
  'Developing with a passion for creating and learning new things.',
  'Strike first, strike hard, no mercy.',
  'Elementary, my dear developer.',
  `Here's Johnny!`,
  'I know how harder it is to be simple than it is to be complex.',
  `I'll get you, my little pretty, and your little code, too!`,
  `I'm not a great developer; I'm just a good developer with great habits.`,
  'I see dead code.',
  'My code never has bugs, it just develops random features.',
  `I'll be back.`,
  'Is this the real life? Is this just fantasy?',
  `Play it, Sam. Play 'As Time Goes By'.`,
  'Muy buenas a todos, guapísimos.',
  'Somebody once told me the world is gonna roll me.',
  `Mom's spaghetti.`,
  'Are you not entertained?',
  'I am inevitable.',
  `Mr. Stark, I don't feel so good.`,
  `Are you Satoru Gojo because you're the strongest?`,
  `Are you the strongest because you are Satoru Gojo?`,
  'Maybe I am a bot.',
  'I am a bot, beep boop.',
  'I am a bot, and I am here to help.',
  'Jarvis, start the code.',
  'I am a software developer, not a magician.',
  `I'm a software developer, not a wizard.`,
  'I am a software developer, not a superhero.',
  'やれやれだぜ.',
  'Turn up the volume, it is time to code.',
];
